FROM maven:3.8.4-openjdk-17 AS build

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

WORKDIR /app

COPY --from=build /app/target/backend-0.0.1-SNAPSHOT.jar .

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/backend-0.0.1-SNAPSHOT.jar"]

#docker build -t student-management-system .
#docker tag student-management-system leelarohith/student-management-system:latest
# docker push leelarohith/student-management-system:latest
